# Generated by Django 4.2.4 on 2023-09-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('post_url', models.URLField()),
                ('currency', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('attributes', models.TextField()),
                ('seller_data', models.TextField()),
                ('media', models.TextField()),
            ],
        ),
    ]
