# Generated by Django 4.2.4 on 2023-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpensooqApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='neighborhood',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
